"""
Data models for Sauda Bot negotiation assistant.
"""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional
from uuid import UUID


class SentimentType(str, Enum):
    """Sentiment types for conversation analysis"""
    FRIENDLY = "friendly"
    FORMAL = "formal"
    TENSE = "tense"
    NEUTRAL = "neutral"


class RelationshipType(str, Enum):
    """Relationship types between trading parties"""
    NEW_CUSTOMER = "new_customer"
    REPEAT_CUSTOMER = "repeat_customer"
    FREQUENT_PARTNER = "frequent_partner"


class NegotiationStyle(str, Enum):
    """Regional negotiation style preferences"""
    DIRECT = "direct"
    INDIRECT = "indirect"
    RELATIONSHIP_FOCUSED = "relationship_focused"
    BUSINESS_FOCUSED = "business_focused"


@dataclass
class Message:
    """Represents a conversation message"""
    id: UUID
    sender_id: UUID
    text: str
    language: str
    timestamp: datetime


@dataclass
class NegotiationState:
    """Current state of a negotiation"""
    commodity: str
    initial_quote: float
    counter_offers: List[float]
    current_price: float
    sentiment: SentimentType
    messages: List[Message]


@dataclass
class RelationshipContext:
    """Context about the relationship between parties"""
    relationship_type: RelationshipType
    transaction_count: int
    last_transaction_date: Optional[datetime]


@dataclass
class FestivalContext:
    """Context about festivals affecting pricing"""
    festival_name: str
    date: datetime
    typical_price_adjustment: float  # Multiplier (e.g., 1.2 for 20% increase)


@dataclass
class CulturalContext:
    """Cultural context for negotiation"""
    language: str
    region: str
    honorifics: List[str]
    relationship_terms: List[str]
    negotiation_style: NegotiationStyle
    festival_context: Optional[FestivalContext]


@dataclass
class NegotiationSuggestion:
    """A negotiation suggestion generated by the LLM"""
    suggested_price: float
    message: str
    rationale: str
    confidence: float


@dataclass
class PriceAggregation:
    """Market price aggregation data"""
    commodity: str
    min_price: float
    max_price: float
    average_price: float
    median_price: float
    std_dev: float
    sample_size: int
    timestamp: datetime
